name: Pre-Release Publish

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: semver
      id: semver
      uses: paulhatch/semantic-version@v4.0.2
      with:
        tag_prefix: "v"
        #branch: master
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        format: "${major}.${minor}.${patch}-beta${increment}"
        change_path: "src/"
        bump_each_commit: true
        namespace: ""
    - run: rm -f ~/.npmrc ; rm -f ./.npmrc ; echo "//registry.npmjs.org/:_authToken=\${{ secrets.NPM2_TOKEN_PUB }}" > ./.npmrc
    - run: |
        git config user.name "GitHub Actions Bot";
        git config user.email "<>";
        echo "Hello $(git config --get user.name)";
    - run: npm run build
    # - run: npm test
    - name: output version
      run: |
        echo "Setting version too: ${{ steps.semver.outputs.version }}";
    - run: npm version ${{ steps.semver.outputs.version }}
    - run: npm config set sign-git-tag true
    - run: npm publish
    - name: cleanup
      if: always()
      run: rm -f ~/.npmrc ; rm -f ./.npmrc;
