name: Publish

on:
  create:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: semver
      id: semver
      uses: paulhatch/semantic-version@v4.0.2
      with:
        tag_prefix: "v"
        #branch: master
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        format: "${major}.${minor}.${patch}"
        change_path: "src/"
        bump_each_commit: false
        namespace: ""
    - run: npm run build
    # - run: npm test
    - name: output version
      run: |
        echo ::debug::setting version too: ${{ steps.semver.outputs.version }}
    - run: npm version version ${{ steps.semver.outputs.version }}
    - run: npm config set sign-git-tag true
    - run: rm -f ~/.npmrc ; rm -f ./.npmrc ; echo "//registry.npmjs.org/:_authToken=\${NPM2_TOKEN_PUB}" > ./.npmrc
    - run: npm publish
    - name: cleanup
      if: always()
      run: rm -f ~/.npmrc ; rm -f ./.npmrc
